import './globals.css'
import { Montserrat } from 'next/font/google'
 
const monserrat = Montserrat({
  weight: '600',
  subsets: ['latin'],
})

export const metadata = {
  title: 'October CLONE',
  description: 'Generated by create next app',
  icons:[
    {
      rel: 'icon',
      type: 'image/svg',
      sizes: '32x32',
      url: './mark.svg',
    },
  ]
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={monserrat.className}>{children}</body>
    </html>
  )
}
